"""add_indexes_to_trading_pairs

Revision ID: 2b964ff1856b
Revises: 124392f5e104
Create Date: 2026-04-15 12:51:47.041864

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b964ff1856b"
down_revision: str | Sequence[str] | None = "124392f5e104"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_trading_pairs_base_asset", "trading_pairs", ["base_asset"], unique=False
    )
    op.create_index(
        "ix_trading_pairs_exchange_id", "trading_pairs", ["exchange_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_trading_pairs_exchange_id", table_name="trading_pairs")
    op.drop_index("ix_trading_pairs_base_asset", table_name="trading_pairs")
    # ### end Alembic commands ###
